/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package dk.andreas.tabvejrny;

public final class R {
    public static final class array {
        public static final int hudType=0x7f060002;
        public static final int hudTypeValues=0x7f060003;
        public static final int posBestem=0x7f060000;
        public static final int posBestemValues=0x7f060001;
        public static final int posValgt1Values=0x7f060006;
        public static final int tabs=0x7f060004;
        public static final int tabsValues=0x7f060005;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int henter=0x7f020000;
        public static final int icon=0x7f020001;
        public static final int kanikkehente=0x7f020002;
        public static final int picture_frame=0x7f020003;
        public static final int prec_nordeuro_9=0x7f020004;
        public static final int vejrhane=0x7f020005;
        public static final int vejrhane2=0x7f020006;
        public static final int vejrhane3=0x7f020007;
        public static final int widget_bg=0x7f020008;
    }
    public static final class id {
        public static final int GlatfoereImageView=0x7f080006;
        public static final int GlatfoereTextView=0x7f080005;
        public static final int NyhederBeskrivelse=0x7f080012;
        public static final int NyhederDato=0x7f080011;
        public static final int NyhederOverskrift=0x7f080010;
        public static final int NyhederTextView=0x7f080007;
        public static final int PrecTypeLegendImageView=0x7f08000a;
        public static final int PrognoseImageView1=0x7f080002;
        public static final int PrognoseImageView2=0x7f080003;
        public static final int PrognoseImageView3=0x7f080004;
        public static final int PrognoseTextView=0x7f080001;
        public static final int RadarImageView=0x7f08000d;
        public static final int RadarTextView=0x7f08000c;
        public static final int about_content=0x7f080000;
        public static final int gallery=0x7f08000b;
        public static final int nyhedsliste=0x7f080008;
        public static final int radar_nedbørstype=0x7f08000f;
        public static final int radar_radar=0x7f08000e;
        public static final int surface=0x7f080013;
        public static final int switcher=0x7f080009;
        public static final int widgetimage=0x7f080014;
        public static final int widgettext=0x7f080015;
    }
    public static final class layout {
        public static final int about=0x7f030000;
        public static final int byvejr=0x7f030001;
        public static final int glatfoere=0x7f030002;
        public static final int main=0x7f030003;
        public static final int nyheder=0x7f030004;
        public static final int preference_category=0x7f030005;
        public static final int radar=0x7f030006;
        public static final int radar2=0x7f030007;
        public static final int row=0x7f030008;
        public static final int webtv=0x7f030009;
        public static final int widget=0x7f03000a;
    }
    public static final class raw {
        public static final int gpsdata=0x7f050000;
        public static final int tabs=0x7f050001;
        public static final int uvtal=0x7f050002;
    }
    public static final class string {
        public static final int about_label=0x7f070008;
        public static final int about_text=0x7f070007;
        public static final int about_title=0x7f070006;
        public static final int app_name=0x7f070000;
        public static final int hello=0x7f070001;
        public static final int posValg1=0x7f070003;
        public static final int posValgDist=0x7f070005;
        public static final int posValgNavn=0x7f070004;
        public static final int widget_name=0x7f070002;
    }
    public static final class xml {
        public static final int settings=0x7f040000;
        public static final int widget=0x7f040001;
    }
}
